### ISSUE TITLE
Question:  multiple languages supports ?

### ISSUE THREAD

**Issue by MaikoTan** [xivapi/ffxiv-datamining#19]
Could this repo support multiple languages like German/French/Japanese ?

**Comment by Hezkezl** [comment]
It certainly _could_...but the "all languages extract" changes the format of the files from how it's shown now. If the file has different language text in it (aka: it's not just numbers), then the language is added to the end of the file name. Otherwise, it's just the normal file name. (Some [examples of the 'all files extract' are here in this screenshot.](https://cdn.discordapp.com/attachments/477631558317244427/778665498187530290/unknown.png))

If we were to redo the layout and change the /csv/ to contain all the languages like the SaintCoinach.cmd extractor outputs them by default, then anyone who's using this repo might find that their stuff breaks because of the change in file names. There's currently 185 people who have this project Starred, 37 forks, and 25 people watching it...and I don't know what anybody uses this project for. I think this was mainly done as a way to keep an archive for a few small projects for some people. I don't know if anybody has any major projects running using this or not :x

I kinda want to say that if you're running a project that requires multiple languages, then you might be better off either using XIVAPI or downloading the SaintCoinach.Cmd extractor from the /ufx/SaintCoinach repo and keeping an extract of the files yourself. I don't believe this is a high demand thing, since you're the first person in over a year to ever ask about it.

If there's a lot of people who want all the different language files available then maybe we can try to accommodate that. But if it's just one person...I'd suggest trying to keep the archive yourself. The most recent extract of all the .csv files is just about 518mb (on disk size), so if that's something you're able to do I'd recommend it :) 

But I'm willing to look at input from other people to see what they think.

**Comment by MaikoTan** [comment]
Thanks for the detailed answer !
I'll try to use XIVAPI in my application, but I think that it is not bad to keep different languages in this repo. Or make some new repos (like `ffxiv-datamining-ko`) such as `ffxiv-datamining-de` or `ffxiv-datamining-ja` or something ?
I asked because I have only Linux, I can't use SaintCoinach directly from bash. And my application would request XIVAPI for more than 1 thousand times, I think read from csvs would decrease running time and obey XIVAPI's policy.
